os:
  editPreset: "nvim-remote"
gui:
  nerdFontsVersion: "3"
  language: en
  theme:
    activeBorderColor:
      - "#7fbbb3"
      - "bold"
    inactiveBorderColor:
      - "#a7c080"
    searchingActiveBorderColor:
      - "#ff966c"
      - "bold"
    optionsTextColor:
      - "#d3c6aa"
    selectedLineBgColor:
      - "#2d3f76"
    cherryPickedCommitFgColor:
      - "#82aaff"
    cherryPickedCommitBgColor:
      - "#c099ff"
    markedBaseCommitFgColor:
      - "#82aaff"
    markedBaseCommitBgColor:
      - "#ffc777"
    unstagedChangesColor:
      - "#c53b53"
    defaultFgColor:
      - "#c8d3f5"
